name: ui_kit
version: 1.0.0
description: The Dart analyzer settings and best practices used internally at Google.
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  app_logger:
    path: ../app_logger
  blocs:
    path: ../blocs
  cached_network_image: ^3.1.0
  dotted_border: ^2.0.0+1
  dropdown_search: ^1.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_pdfview: ^1.2.2
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.1+1
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  google_api_headers: ^1.3.0
  google_maps_webservice: ^0.0.19
  intl: ^0.19.0
  ionicons: ^0.1.2
  nil: ^1.1.1
  popover: ^0.2.6+3
  repositories:
    path: ../repositories
  shared:
    path: ../shared
  url_launcher: ^6.0.16
  view_models:
    path: ../view_models
