name: api_services
version: 1.0.0
description: Services package
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  app_logger:
    path: ../app_logger
  chopper: ^4.0.5
  equatable: ^2.0.3
  firebase_messaging: ^11.4.0
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  json_annotation: ^4.5.0
  path: ^1.8.0
  repositories:
    path: ../repositories
  shared:
    path: ../shared
  view_models:
    path: ../view_models

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^1.0.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
