// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'agency.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Agency _$AgencyFromJson(Map<String, dynamic> json) => Agency(
      json['id'] as String?,
      json['orgName'] as String?,
      json['orgSlogan'] as String?,
      json['phone'] as String?,
      json['country'] as String?,
      json['styleURL'] as String?,
      json['link'] as String?,
      json['agencyAbonnSettings'] as String?,
      json['agencyTigrisSettings'] as String?,
      json['sfOrgId'] as String?,
      json['sfLEId'] as String?,
      json['sfRecordId'] as String?,
      json['isGetLEorg'] as bool?,
      json['isRootAccount'] as bool?,
      json['fieldSet'] as String?,
      json['googleTagManagerId'] as String?,
      json['shippingLongitude'] as String?,
      json['shippingLatitude'] as String?,
      json['website'] as String?,
      json['careerMsg'] as String?,
      json['menuSettings'] as String?,
      json['expirationPeriodEmployee'] as String?,
      json['expirationPeriodApplicant'] as String?,
      json['fieldSetForProfile'] as String?,
      json['extendPermissionMessages'] as String?,
      json['recordTypesIds'] as String?,
      json['picklistData'] as String?,
      json['createdAt'] as String?,
      json['updatedAt'] as String?,
      json['headerLogoUrl'] as String?,
      json['zip'] as String?,
      json['description'] as String?,
      json['welcomeMsg'] as String?,
      json['movieAfterInvite'] as String?,
      json['styleJSON'] == null
          ? null
          : StyleJson.fromJson(json['styleJSON'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$AgencyToJson(Agency instance) => <String, dynamic>{
      'id': instance.id,
      'orgName': instance.orgName,
      'orgSlogan': instance.orgSlogan,
      'phone': instance.phone,
      'country': instance.country,
      'styleURL': instance.styleURL,
      'link': instance.link,
      'agencyAbonnSettings': instance.agencyAbonnSettings,
      'agencyTigrisSettings': instance.agencyTigrisSettings,
      'sfOrgId': instance.sfOrgId,
      'sfLEId': instance.sfLEId,
      'sfRecordId': instance.sfRecordId,
      'isGetLEorg': instance.isGetLEorg,
      'isRootAccount': instance.isRootAccount,
      'fieldSet': instance.fieldSet,
      'googleTagManagerId': instance.googleTagManagerId,
      'shippingLongitude': instance.shippingLongitude,
      'shippingLatitude': instance.shippingLatitude,
      'website': instance.website,
      'careerMsg': instance.careerMsg,
      'menuSettings': instance.menuSettings,
      'expirationPeriodEmployee': instance.expirationPeriodEmployee,
      'expirationPeriodApplicant': instance.expirationPeriodApplicant,
      'fieldSetForProfile': instance.fieldSetForProfile,
      'extendPermissionMessages': instance.extendPermissionMessages,
      'recordTypesIds': instance.recordTypesIds,
      'picklistData': instance.picklistData,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'headerLogoUrl': instance.headerLogoUrl,
      'zip': instance.zip,
      'description': instance.description,
      'welcomeMsg': instance.welcomeMsg,
      'movieAfterInvite': instance.movieAfterInvite,
      'styleJSON': instance.styleJSON,
    };
