// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hours.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Hours _$HoursFromJson(Map<String, dynamic> json) => Hours(
      id: json['id'] as String?,
      name: json['name'] as String?,
      date: json['date'] as String?,
      amountOfHours: (json['amountOfHours'] as num?)?.toDouble(),
      description: json['description'] as String?,
      sfOrgId: json['sfOrgId'] as String?,
      isUpsertApp: json['isUpsertApp'] as bool?,
      isGetLEorg: json['isGetLEorg'] as bool?,
      isDeleted: json['isDeleted'] as bool?,
      sfLEId: json['sfLEId'] as String?,
      sfRecordId: json['sfRecordId'] as String?,
      uurloonBijUitzending: json['uurloonBijUitzending'] as String?,
      loonPerc: (json['loonPerc'] as num?)?.toDouble(),
      unraveling: json['unraveling'] as bool?,
      createdAt: json['createdAt'] as String?,
      projectId: json['projectId'] as String?,
      tarifId: json['tarifId'] as String?,
      timesheetId: json['timesheetId'] as String?,
      projectIdAlId: json['projectIdAlId'] as String?,
      projectIdAlName: json['projectIdAlName'] as String?,
      timesheetIdAlId: json['timesheetIdAlId'] as String?,
      timesheetIdAlStartDate: json['timesheetIdAlStartDate'] as String?,
      timesheetIdAlEndDate: json['timesheetIdAlEndDate'] as String?,
      tarifIdAlId: json['tarifId__al.id'] as String?,
      tarifIdAlName: json['tarifId__al.name'] as String?,
      tarifIdAlCompensatPrc: json['tarifIdAlCompensatPrc'] as int?,
      tarifIdAlInvoicePercentage: json['tarifIdAlInvoicePercentage'] as int?,
      tarifIdAlValidFrom: json['tarifIdAlValidFrom'] as String?,
      tarifIdAlValidUntil: json['tarifIdAlValidUntil'] as String?,
      tarifIdAlInvoiceFactor: json['tarifIdAlInvoiceFactor'] as String?,
      tarifIdAlInvoiceBedrag: json['tarifIdAlInvoiceBedrag'] as String?,
      tarifIdAlInvoiceFactorPremie:
          json['tarifIdAlInvoiceFactorPremie'] as String?,
      tarifIdAlRaise: json['tarifIdAlRaise'] as String?,
      tarifIdAlMaxUsagePerDay: json['tarifIdAlMaxUsagePerDay'] as String?,
      tarifIdAlMaxUsagePerWeek: json['tarifIdAlMaxUsagePerWeek'] as String?,
    );

Map<String, dynamic> _$HoursToJson(Hours instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'date': instance.date,
      'amountOfHours': instance.amountOfHours,
      'description': instance.description,
      'sfOrgId': instance.sfOrgId,
      'isUpsertApp': instance.isUpsertApp,
      'isGetLEorg': instance.isGetLEorg,
      'isDeleted': instance.isDeleted,
      'sfLEId': instance.sfLEId,
      'sfRecordId': instance.sfRecordId,
      'uurloonBijUitzending': instance.uurloonBijUitzending,
      'loonPerc': instance.loonPerc,
      'unraveling': instance.unraveling,
      'createdAt': instance.createdAt,
      'projectId': instance.projectId,
      'tarifId': instance.tarifId,
      'timesheetId': instance.timesheetId,
      'projectIdAlId': instance.projectIdAlId,
      'projectIdAlName': instance.projectIdAlName,
      'timesheetIdAlId': instance.timesheetIdAlId,
      'timesheetIdAlStartDate': instance.timesheetIdAlStartDate,
      'timesheetIdAlEndDate': instance.timesheetIdAlEndDate,
      'tarifId__al.id': instance.tarifIdAlId,
      'tarifId__al.name': instance.tarifIdAlName,
      'tarifIdAlCompensatPrc': instance.tarifIdAlCompensatPrc,
      'tarifIdAlInvoicePercentage': instance.tarifIdAlInvoicePercentage,
      'tarifIdAlValidFrom': instance.tarifIdAlValidFrom,
      'tarifIdAlValidUntil': instance.tarifIdAlValidUntil,
      'tarifIdAlInvoiceFactor': instance.tarifIdAlInvoiceFactor,
      'tarifIdAlInvoiceBedrag': instance.tarifIdAlInvoiceBedrag,
      'tarifIdAlInvoiceFactorPremie': instance.tarifIdAlInvoiceFactorPremie,
      'tarifIdAlRaise': instance.tarifIdAlRaise,
      'tarifIdAlMaxUsagePerDay': instance.tarifIdAlMaxUsagePerDay,
      'tarifIdAlMaxUsagePerWeek': instance.tarifIdAlMaxUsagePerWeek,
    };
