// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'records.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Records _$RecordsFromJson(Map<String, dynamic> json) => Records(
      json['id'] as String?,
      json['firstName'] as String?,
      json['lastName'] as String?,
      json['birthdate'] as String?,
      json['email'] as String?,
      json['sfOrgId'] as String?,
      json['photoURL'] as String?,
      json['isUpsertApp'] as bool?,
      json['isGetLEorg'] as bool?,
      json['registeredOnApp'] as bool?,
      json['sfLEId'] as String?,
      json['sfRecordId'] as String?,
      json['bsnNummer'] as String?,
      json['initialen'] as String?,
      json['idType'] as String?,
      json['geboorteland'] as String?,
      json['idNummer'] as String?,
      json['bankIBAN'] as String?,
      json['salaryType'] as String?,
      json['dienstverbandStatus'] as String?,
      json['deeltijdpercentage'] as int?,
      json['sector'] as int?,
      json['tijdvakTabel'] as String?,
      json['mailingcity'] as String?,
      json['gender'] as String?,
      json['mailingLongitude'] as String?,
      json['mailingLatitude'] as String?,
      json['beschikbaarheid'] as bool?,
      json['needOpportunityNotifications'] as bool?,
      json['multiOwnTransport'] as String?,
      json['mailingState'] as String?,
      json['mailingCountry'] as String?,
      json['mailingPostalCode'] as String?,
      json['mailingStreet'] as String?,
      json['gewensteFuncties'] as String?,
      json['idVerloopdatum'] as String?,
      json['loonheffingskorting'] as bool?,
      json['createdAt'] as String?,
      json['updatedAt'] as String?,
      json['agencyId'] as String?,
      json['individualRefId'] as String?,
      json['userId'] as String?,
      json['drivingLicense'] as String?,
      json['mobile'] as String?,
      json['description'] as String?,
      json['feedbackSummarize'] as String?,
      json['indienstDat'] as String?,
      json['nationaliteit'] as String?,
      json['invloedVerzekeringsplicht'] as String?,
      json['codeCao'] as int?,
      json['waoWia'] as bool?,
      json['ww'] as bool?,
      json['zw'] as bool?,
      json['codeIabZvw'] as int?,
      json['codeZvw'] as String?,
      json['jaarloonBT'] as String?,
      json['lhk'] as bool?,
      json['loonheffing'] as bool?,
      json['kleurTabel'] as int?,
      json['soortInkomen'] as int?,
      json['fase'] as String?,
      json['blockedReservations'] as String?,
      json['availableHours'] as int?,
      json['periodOfNotice'] as String?,
      json['availableHoursPeriod'] as String?,
      json['applyWageTaxLevyfrom'] as String?,
    );

Map<String, dynamic> _$RecordsToJson(Records instance) => <String, dynamic>{
      'id': instance.id,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'birthdate': instance.birthdate,
      'email': instance.email,
      'sfOrgId': instance.sfOrgId,
      'photoURL': instance.photoURL,
      'isUpsertApp': instance.isUpsertApp,
      'isGetLEorg': instance.isGetLEorg,
      'registeredOnApp': instance.registeredOnApp,
      'sfLEId': instance.sfLEId,
      'sfRecordId': instance.sfRecordId,
      'bsnNummer': instance.bsnNummer,
      'initialen': instance.initialen,
      'idType': instance.idType,
      'geboorteland': instance.geboorteland,
      'idNummer': instance.idNummer,
      'bankIBAN': instance.bankIBAN,
      'salaryType': instance.salaryType,
      'dienstverbandStatus': instance.dienstverbandStatus,
      'deeltijdpercentage': instance.deeltijdpercentage,
      'sector': instance.sector,
      'tijdvakTabel': instance.tijdvakTabel,
      'mailingcity': instance.mailingcity,
      'gender': instance.gender,
      'mailingLongitude': instance.mailingLongitude,
      'mailingLatitude': instance.mailingLatitude,
      'beschikbaarheid': instance.beschikbaarheid,
      'needOpportunityNotifications': instance.needOpportunityNotifications,
      'multiOwnTransport': instance.multiOwnTransport,
      'mailingState': instance.mailingState,
      'mailingCountry': instance.mailingCountry,
      'mailingPostalCode': instance.mailingPostalCode,
      'mailingStreet': instance.mailingStreet,
      'gewensteFuncties': instance.gewensteFuncties,
      'idVerloopdatum': instance.idVerloopdatum,
      'loonheffingskorting': instance.loonheffingskorting,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'agencyId': instance.agencyId,
      'individualRefId': instance.individualRefId,
      'userId': instance.userId,
      'drivingLicense': instance.drivingLicense,
      'mobile': instance.mobile,
      'description': instance.description,
      'feedbackSummarize': instance.feedbackSummarize,
      'indienstDat': instance.indienstDat,
      'nationaliteit': instance.nationaliteit,
      'invloedVerzekeringsplicht': instance.invloedVerzekeringsplicht,
      'codeCao': instance.codeCao,
      'waoWia': instance.waoWia,
      'ww': instance.ww,
      'zw': instance.zw,
      'codeIabZvw': instance.codeIabZvw,
      'codeZvw': instance.codeZvw,
      'jaarloonBT': instance.jaarloonBT,
      'lhk': instance.lhk,
      'loonheffing': instance.loonheffing,
      'kleurTabel': instance.kleurTabel,
      'soortInkomen': instance.soortInkomen,
      'fase': instance.fase,
      'blockedReservations': instance.blockedReservations,
      'availableHours': instance.availableHours,
      'periodOfNotice': instance.periodOfNotice,
      'availableHoursPeriod': instance.availableHoursPeriod,
      'applyWageTaxLevyfrom': instance.applyWageTaxLevyfrom,
    };
