// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'total_reservation.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TotalReservation _$TotalReservationFromJson(Map<String, dynamic> json) =>
    TotalReservation(
      json['id'] as String?,
      json['FD_eind'] as String?,
      json['KV_eind'] as String?,
      json['ADV_eind'] as String?,
      json['TvT_eind_uren'] as String?,
      json['VG_eind'] as String?,
      json['VG_eind_temp'] as String?,
      json['VDw_eind'] as String?,
      json['VDb_eind'] as String?,
      json['VDt_eind'] as String?,
      json['FD_in_uren'] as String?,
      json['FD_in_uren_temp'] as String?,
      json['KV_in_uren'] as String?,
      json['KV_in_uren_temp'] as String?,
      json['ADV_in_uren'] as String?,
      json['ADV_in_uren_temp'] as String?,
      json['TvT_in_uren'] as String?,
      json['TvT_in_uren_temp'] as String?,
      json['VG_in_uren'] as String?,
      json['VDw_in_uren'] as String?,
      json['VDw_in_uren_temp'] as String?,
      json['VDb_in_uren'] as String?,
      json['VDb_in_uren_temp'] as String?,
      json['VDt_in_uren'] as String?,
      json['VDt_in_uren_temp'] as String?,
      json['totalReservationSf'] as String?,
      json['nmbrsID'] as String?,
      json['sfLEId'] as String?,
      json['isGetLEorg'] as bool?,
      json['sfOrgId'] as String?,
      json['isDeleted'] as bool?,
      json['sfRecordId'] as String?,
      json['createdAt'] as String?,
      json['updatedAt'] as String?,
      json['employeeId'] as String?,
    );

Map<String, dynamic> _$TotalReservationToJson(TotalReservation instance) =>
    <String, dynamic>{
      'id': instance.id,
      'FD_eind': instance.fDEind,
      'KV_eind': instance.kVEind,
      'ADV_eind': instance.aDVEind,
      'TvT_eind_uren': instance.tvTEindUren,
      'VG_eind': instance.vGEind,
      'VG_eind_temp': instance.vGEindTemp,
      'VDw_eind': instance.vDwEind,
      'VDb_eind': instance.vDbEind,
      'VDt_eind': instance.vDtEind,
      'FD_in_uren': instance.fDInUren,
      'FD_in_uren_temp': instance.fDInUrenTemp,
      'KV_in_uren': instance.kVInUren,
      'KV_in_uren_temp': instance.kVInUrenTemp,
      'ADV_in_uren': instance.aDVInUren,
      'ADV_in_uren_temp': instance.aDVInUrenTemp,
      'TvT_in_uren': instance.tvTInUren,
      'TvT_in_uren_temp': instance.tvTInUrenTemp,
      'VG_in_uren': instance.vGInUren,
      'VDw_in_uren': instance.vDwInUren,
      'VDw_in_uren_temp': instance.vDwInUrenTemp,
      'VDb_in_uren': instance.vDbInUren,
      'VDb_in_uren_temp': instance.vDbInUrenTemp,
      'VDt_in_uren': instance.vDtInUren,
      'VDt_in_uren_temp': instance.vDtInUrenTemp,
      'totalReservationSf': instance.totalReservationSf,
      'nmbrsID': instance.nmbrsID,
      'sfLEId': instance.sfLEId,
      'isGetLEorg': instance.isGetLEorg,
      'sfOrgId': instance.sfOrgId,
      'isDeleted': instance.isDeleted,
      'sfRecordId': instance.sfRecordId,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'employeeId': instance.employeeId,
    };
