// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserInfo _$UserInfoFromJson(Map<String, dynamic> json) => UserInfo(
      json['id'] as String?,
      json['email'] as String?,
      json['username'] as String?,
      json['firstName'] as String?,
      json['lastName'] as String?,
      json['type'] as String?,
      json['activated'] as bool?,
      json['profilePhotoName'] as String?,
      json['preferredLanguage'] as String?,
      json['resetPasswordToken'] as String?,
      json['cookieconsent'] as String?,
      json['lastSeenInApp'] as String?,
      json['viewModeEC'] as String?,
      json['isRoot'] as bool?,
      json['is2FA'] as bool?,
      json['resetAttempt'] as String?,
      json['appErrorInfo'] as String?,
      json['birthDate'] as String?,
      json['fullName'] as String?,
      json['nickName'] as String?,
      json['nationality'] as String?,
      json['phone'] as String?,
      json['addressCountry'] as String?,
      json['addressProvince'] as String?,
      json['addressStreet'] as String?,
      json['addressPostalCode'] as String?,
      json['desiredSalary'] as String?,
      json['desiredFunction'] as String?,
      json['maxTravelTimeMinutes'] as String?,
      json['createdAt'] as String?,
      json['updatedAt'] as String?,
      json['currentAgencyId'] as String?,
    );

Map<String, dynamic> _$UserInfoToJson(UserInfo instance) => <String, dynamic>{
      'id': instance.id,
      'email': instance.email,
      'username': instance.username,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'type': instance.type,
      'activated': instance.activated,
      'profilePhotoName': instance.profilePhotoName,
      'preferredLanguage': instance.preferredLanguage,
      'resetPasswordToken': instance.resetPasswordToken,
      'cookieconsent': instance.cookieconsent,
      'lastSeenInApp': instance.lastSeenInApp,
      'viewModeEC': instance.viewModeEC,
      'isRoot': instance.isRoot,
      'is2FA': instance.is2FA,
      'resetAttempt': instance.resetAttempt,
      'appErrorInfo': instance.appErrorInfo,
      'birthDate': instance.birthDate,
      'fullName': instance.fullName,
      'nickName': instance.nickName,
      'nationality': instance.nationality,
      'phone': instance.phone,
      'addressCountry': instance.addressCountry,
      'addressProvince': instance.addressProvince,
      'addressStreet': instance.addressStreet,
      'addressPostalCode': instance.addressPostalCode,
      'desiredSalary': instance.desiredSalary,
      'desiredFunction': instance.desiredFunction,
      'maxTravelTimeMinutes': instance.maxTravelTimeMinutes,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'currentAgencyId': instance.currentAgencyId,
    };
