name: repositories
version: 1.0.0
description: Repository package
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  api_services:
    path: ../api_services
  app_logger:
    path: ../app_logger
  easy_localization: ^3.0.0
  event: ^2.1.2
  # file_picker: ^6.2.1
  flutter:
    sdk: flutter
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  json_annotation: ^4.5.0
  local_auth: ^2.1.0
  path_provider: ^2.0.9
  result_type: 0.1.0
  shared:
    path: ../shared
  view_models:
    path: ../view_models

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1