// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'agency_data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_AgencyDataModel _$$_AgencyDataModelFromJson(Map<String, dynamic> json) =>
    _$_AgencyDataModel(
      id: json['id'] as String?,
      orgName: json['orgName'] as String?,
      orgSlogan: json['orgSlogan'] as String?,
      phone: json['phone'] as String?,
      country: json['country'] as String?,
      styleURL: json['styleURL'] as String?,
      link: json['link'] as String?,
      agencyAbonnSettings: json['agencyAbonnSettings'] as String?,
      agencyTigrisSettings: json['agencyTigrisSettings'] as String?,
      sfOrgId: json['sfOrgId'] as String?,
      sfLEId: json['sfLEId'] as String?,
      sfRecordId: json['sfRecordId'] as String?,
      isGetLEorg: json['isGetLEorg'] as bool?,
      isRootAccount: json['isRootAccount'] as bool?,
      fieldSet: json['fieldSet'] as String?,
      googleTagManagerId: json['googleTagManagerId'] as String?,
      shippingLongitude: json['shippingLongitude'] as String?,
      shippingLatitude: json['shippingLatitude'] as String?,
      website: json['website'] as String?,
      careerMsg: json['careerMsg'] as String?,
      menuSettings: json['menuSettings'] as String?,
      expirationPeriodEmployee: json['expirationPeriodEmployee'] as String?,
      expirationPeriodApplicant: json['expirationPeriodApplicant'] as String?,
      fieldSetForProfile: json['fieldSetForProfile'] as String?,
      extendPermissionMessages: json['extendPermissionMessages'] as String?,
      recordTypesIds: json['recordTypesIds'] as String?,
      picklistData: json['picklistData'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      headerLogoUrl: json['headerLogoUrl'] as String?,
      zip: json['zip'] as String?,
      description: json['description'] as String?,
      welcomeMsg: json['welcomeMsg'] as String?,
      movieAfterInvite: json['movieAfterInvite'] as String?,
      styleJson: json['styleJson'] == null
          ? null
          : StyleJsonDataModel.fromJson(
              json['styleJson'] as Map<String, dynamic>),
      tigrisClosedYearC: json['tigrisClosedYearC'] as int?,
      tigrisFutureApproveTimesheetC:
          json['tigrisFutureApproveTimesheetC'] as bool?,
      tigrisSeparating38hoursIntoEqualPartsC:
          json['tigrisSeparating38hoursIntoEqualPartsC'] as bool?,
      tigrisTSPerReslevelC: json['tigrisTSPerReslevelC'] as bool?,
      tigrisDagReslevelC: json['tigrisDagReslevelC'] as bool?,
      tigrisPresenterenFdC: json['tigrisPresenterenFdC'] as bool?,
      tigrisFDresC: json['tigrisFDresC'] as bool?,
      tigrisPresenterenWDCc: json['tigrisPresenterenWDCc'] as bool?,
      tigrisPresenterenKVc: json['tigrisPresenterenKVc'] as bool?,
      tigrisPresenterenADVc: json['tigrisPresenterenADVc'] as bool?,
      tigrisADVreserverenC: json['tigrisADVreserverenC'] as bool?,
      tigrisPresenterenTvTc: json['tigrisPresenterenTvTc'] as bool?,
      tigrisTvTreserverenC: json['tigrisTvTreserverenC'] as bool?,
      tigrisPresenterenVDTc: json['tigrisPresenterenVDTc'] as bool?,
      tigrisPresenterenVDwc: json['tigrisPresenterenVDwc'] as bool?,
      tigrisPresenterenVDbc: json['tigrisPresenterenVDbc'] as bool?,
      tigrisPresenterenVGc: json['tigrisPresenterenVGc'] as bool?,
      tigrisReservationHalfEvenRoundingFromC:
          json['tigrisReservationHalfEvenRoundingFromC'] as String?,
      googlePlacesApiKey: json['googlePlacesApiKey'] as String?,
    );

Map<String, dynamic> _$$_AgencyDataModelToJson(_$_AgencyDataModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'orgName': instance.orgName,
      'orgSlogan': instance.orgSlogan,
      'phone': instance.phone,
      'country': instance.country,
      'styleURL': instance.styleURL,
      'link': instance.link,
      'agencyAbonnSettings': instance.agencyAbonnSettings,
      'agencyTigrisSettings': instance.agencyTigrisSettings,
      'sfOrgId': instance.sfOrgId,
      'sfLEId': instance.sfLEId,
      'sfRecordId': instance.sfRecordId,
      'isGetLEorg': instance.isGetLEorg,
      'isRootAccount': instance.isRootAccount,
      'fieldSet': instance.fieldSet,
      'googleTagManagerId': instance.googleTagManagerId,
      'shippingLongitude': instance.shippingLongitude,
      'shippingLatitude': instance.shippingLatitude,
      'website': instance.website,
      'careerMsg': instance.careerMsg,
      'menuSettings': instance.menuSettings,
      'expirationPeriodEmployee': instance.expirationPeriodEmployee,
      'expirationPeriodApplicant': instance.expirationPeriodApplicant,
      'fieldSetForProfile': instance.fieldSetForProfile,
      'extendPermissionMessages': instance.extendPermissionMessages,
      'recordTypesIds': instance.recordTypesIds,
      'picklistData': instance.picklistData,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'headerLogoUrl': instance.headerLogoUrl,
      'zip': instance.zip,
      'description': instance.description,
      'welcomeMsg': instance.welcomeMsg,
      'movieAfterInvite': instance.movieAfterInvite,
      'styleJson': instance.styleJson,
      'tigrisClosedYearC': instance.tigrisClosedYearC,
      'tigrisFutureApproveTimesheetC': instance.tigrisFutureApproveTimesheetC,
      'tigrisSeparating38hoursIntoEqualPartsC':
          instance.tigrisSeparating38hoursIntoEqualPartsC,
      'tigrisTSPerReslevelC': instance.tigrisTSPerReslevelC,
      'tigrisDagReslevelC': instance.tigrisDagReslevelC,
      'tigrisPresenterenFdC': instance.tigrisPresenterenFdC,
      'tigrisFDresC': instance.tigrisFDresC,
      'tigrisPresenterenWDCc': instance.tigrisPresenterenWDCc,
      'tigrisPresenterenKVc': instance.tigrisPresenterenKVc,
      'tigrisPresenterenADVc': instance.tigrisPresenterenADVc,
      'tigrisADVreserverenC': instance.tigrisADVreserverenC,
      'tigrisPresenterenTvTc': instance.tigrisPresenterenTvTc,
      'tigrisTvTreserverenC': instance.tigrisTvTreserverenC,
      'tigrisPresenterenVDTc': instance.tigrisPresenterenVDTc,
      'tigrisPresenterenVDwc': instance.tigrisPresenterenVDwc,
      'tigrisPresenterenVDbc': instance.tigrisPresenterenVDbc,
      'tigrisPresenterenVGc': instance.tigrisPresenterenVGc,
      'tigrisReservationHalfEvenRoundingFromC':
          instance.tigrisReservationHalfEvenRoundingFromC,
      'googlePlacesApiKey': instance.googlePlacesApiKey,
    };
