import 'package:freezed_annotation/freezed_annotation.dart';

part 'records_data_model.freezed.dart';
part 'records_data_model.g.dart';

@freezed
class RecordsDataModel with _$RecordsDataModel {
  const factory RecordsDataModel({
    String? id,
    String? firstName,
    String? lastName,
    String? birthdate,
    String? email,
    String? sfOrgId,
    String? photoURL,
    bool? isUpsertApp,
    bool? isGetLEorg,
    bool? registeredOnApp,
    String? sfLEId,
    String? sfRecordId,
    String? bsnNummer,
    String? initialen,
    String? idType,
    String? geboorteland,
    String? idNummer,
    String? bankIBAN,
    String? salaryType,
    String? dienstverbandStatus,
    int? deeltijdpercentage,
    int? sector,
    String? tijdvakTabel,
    String? mailingcity,
    String? gender,
    String? mailingLongitude,
    String? mailingLatitude,
    bool? beschikbaarheid,
    bool? needOpportunityNotifications,
    String? multiOwnTransport,
    String? mailingState,
    String? mailingCountry,
    String? mailingPostalCode,
    String? mailingStreet,
    String? gewensteFuncties,
    String? idVerloopdatum,
    bool? loonheffingskorting,
    String? createdAt,
    String? updatedAt,
    String? agencyId,
    String? individualRefId,
    String? userId,
    String? drivingLicense,
    String? mobile,
    String? description,
    String? feedbackSummarize,
    String? indienstDat,
    String? nationaliteit,
    String? invloedVerzekeringsplicht,
    int? codeCao,
    bool? waoWia,
    bool? ww,
    bool? zw,
    int? codeIabZvw,
    String? codeZvw,
    String? jaarloonBT,
    bool? lhk,
    bool? loonheffing,
    int? kleurTabel,
    int? soortInkomen,
    String? fase,
    String? blockedReservations,
    int? availableHours,
    String? periodOfNotice,
    String? availableHoursPeriod,
    String? applyWageTaxLevyfrom,
  }) = _RecordsDataModel;

  factory RecordsDataModel.fromJson(Map<String, dynamic> json) =>
      _$RecordsDataModelFromJson(json);
}
