// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'records_data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_RecordsDataModel _$$_RecordsDataModelFromJson(Map<String, dynamic> json) =>
    _$_RecordsDataModel(
      id: json['id'] as String?,
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      birthdate: json['birthdate'] as String?,
      email: json['email'] as String?,
      sfOrgId: json['sfOrgId'] as String?,
      photoURL: json['photoURL'] as String?,
      isUpsertApp: json['isUpsertApp'] as bool?,
      isGetLEorg: json['isGetLEorg'] as bool?,
      registeredOnApp: json['registeredOnApp'] as bool?,
      sfLEId: json['sfLEId'] as String?,
      sfRecordId: json['sfRecordId'] as String?,
      bsnNummer: json['bsnNummer'] as String?,
      initialen: json['initialen'] as String?,
      idType: json['idType'] as String?,
      geboorteland: json['geboorteland'] as String?,
      idNummer: json['idNummer'] as String?,
      bankIBAN: json['bankIBAN'] as String?,
      salaryType: json['salaryType'] as String?,
      dienstverbandStatus: json['dienstverbandStatus'] as String?,
      deeltijdpercentage: json['deeltijdpercentage'] as int?,
      sector: json['sector'] as int?,
      tijdvakTabel: json['tijdvakTabel'] as String?,
      mailingcity: json['mailingcity'] as String?,
      gender: json['gender'] as String?,
      mailingLongitude: json['mailingLongitude'] as String?,
      mailingLatitude: json['mailingLatitude'] as String?,
      beschikbaarheid: json['beschikbaarheid'] as bool?,
      needOpportunityNotifications:
          json['needOpportunityNotifications'] as bool?,
      multiOwnTransport: json['multiOwnTransport'] as String?,
      mailingState: json['mailingState'] as String?,
      mailingCountry: json['mailingCountry'] as String?,
      mailingPostalCode: json['mailingPostalCode'] as String?,
      mailingStreet: json['mailingStreet'] as String?,
      gewensteFuncties: json['gewensteFuncties'] as String?,
      idVerloopdatum: json['idVerloopdatum'] as String?,
      loonheffingskorting: json['loonheffingskorting'] as bool?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      agencyId: json['agencyId'] as String?,
      individualRefId: json['individualRefId'] as String?,
      userId: json['userId'] as String?,
      drivingLicense: json['drivingLicense'] as String?,
      mobile: json['mobile'] as String?,
      description: json['description'] as String?,
      feedbackSummarize: json['feedbackSummarize'] as String?,
      indienstDat: json['indienstDat'] as String?,
      nationaliteit: json['nationaliteit'] as String?,
      invloedVerzekeringsplicht: json['invloedVerzekeringsplicht'] as String?,
      codeCao: json['codeCao'] as int?,
      waoWia: json['waoWia'] as bool?,
      ww: json['ww'] as bool?,
      zw: json['zw'] as bool?,
      codeIabZvw: json['codeIabZvw'] as int?,
      codeZvw: json['codeZvw'] as String?,
      jaarloonBT: json['jaarloonBT'] as String?,
      lhk: json['lhk'] as bool?,
      loonheffing: json['loonheffing'] as bool?,
      kleurTabel: json['kleurTabel'] as int?,
      soortInkomen: json['soortInkomen'] as int?,
      fase: json['fase'] as String?,
      blockedReservations: json['blockedReservations'] as String?,
      availableHours: json['availableHours'] as int?,
      periodOfNotice: json['periodOfNotice'] as String?,
      availableHoursPeriod: json['availableHoursPeriod'] as String?,
      applyWageTaxLevyfrom: json['applyWageTaxLevyfrom'] as String?,
    );

Map<String, dynamic> _$$_RecordsDataModelToJson(_$_RecordsDataModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'birthdate': instance.birthdate,
      'email': instance.email,
      'sfOrgId': instance.sfOrgId,
      'photoURL': instance.photoURL,
      'isUpsertApp': instance.isUpsertApp,
      'isGetLEorg': instance.isGetLEorg,
      'registeredOnApp': instance.registeredOnApp,
      'sfLEId': instance.sfLEId,
      'sfRecordId': instance.sfRecordId,
      'bsnNummer': instance.bsnNummer,
      'initialen': instance.initialen,
      'idType': instance.idType,
      'geboorteland': instance.geboorteland,
      'idNummer': instance.idNummer,
      'bankIBAN': instance.bankIBAN,
      'salaryType': instance.salaryType,
      'dienstverbandStatus': instance.dienstverbandStatus,
      'deeltijdpercentage': instance.deeltijdpercentage,
      'sector': instance.sector,
      'tijdvakTabel': instance.tijdvakTabel,
      'mailingcity': instance.mailingcity,
      'gender': instance.gender,
      'mailingLongitude': instance.mailingLongitude,
      'mailingLatitude': instance.mailingLatitude,
      'beschikbaarheid': instance.beschikbaarheid,
      'needOpportunityNotifications': instance.needOpportunityNotifications,
      'multiOwnTransport': instance.multiOwnTransport,
      'mailingState': instance.mailingState,
      'mailingCountry': instance.mailingCountry,
      'mailingPostalCode': instance.mailingPostalCode,
      'mailingStreet': instance.mailingStreet,
      'gewensteFuncties': instance.gewensteFuncties,
      'idVerloopdatum': instance.idVerloopdatum,
      'loonheffingskorting': instance.loonheffingskorting,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'agencyId': instance.agencyId,
      'individualRefId': instance.individualRefId,
      'userId': instance.userId,
      'drivingLicense': instance.drivingLicense,
      'mobile': instance.mobile,
      'description': instance.description,
      'feedbackSummarize': instance.feedbackSummarize,
      'indienstDat': instance.indienstDat,
      'nationaliteit': instance.nationaliteit,
      'invloedVerzekeringsplicht': instance.invloedVerzekeringsplicht,
      'codeCao': instance.codeCao,
      'waoWia': instance.waoWia,
      'ww': instance.ww,
      'zw': instance.zw,
      'codeIabZvw': instance.codeIabZvw,
      'codeZvw': instance.codeZvw,
      'jaarloonBT': instance.jaarloonBT,
      'lhk': instance.lhk,
      'loonheffing': instance.loonheffing,
      'kleurTabel': instance.kleurTabel,
      'soortInkomen': instance.soortInkomen,
      'fase': instance.fase,
      'blockedReservations': instance.blockedReservations,
      'availableHours': instance.availableHours,
      'periodOfNotice': instance.periodOfNotice,
      'availableHoursPeriod': instance.availableHoursPeriod,
      'applyWageTaxLevyfrom': instance.applyWageTaxLevyfrom,
    };
