name: blocs
version: 1.0.0
description: Blocks package
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  app_links: ^6.4.0
  app_logger:
    path: ../app_logger
  auto_route: ^3.2.4
  bloc_concurrency: ^0.3.0
  easy_localization: ^3.0.0
  # file_picker: ^6.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  json_annotation: ^4.5.0
  permission_handler: ^11.4.0
  repositories:
    path: ../repositories
  shared:
    path: ../shared
  stream_transform: ^2.0.0
  ui_kit:
    path: ../ui_kit
  uuid: ^3.0.6
  view_models:
    path: ../view_models

dev_dependencies:
  # Code generation
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter

  # Data model and serialization
  freezed: ^3.0.0-0.0.dev

  # DI
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  mocktail: ^1.0.3

  # Utils
  result_type: 0.1.0

flutter:
  uses-material-design: true
